### ISSUE TITLE
Fails to build on Windows

### ISSUE THREAD

**Issue by dacobo** [wyhaya/tauri-plugin-theme#18]
My team is currently getting the following build error when trying to attach this plugin:

```
error[E0433]: failed to resolve: could not find `Graphics` in `Win32`
  --> ...\tauri-plugin-theme-2.1.1\src\platform\windows.rs:52:13
   |
52 |             Graphics::Dwm::{DwmSetWindowAttribute, DWMWA_USE_IMMERSIVE_DARK_MODE},
   |             ^^^^^^^^ could not find `Graphics` in `Win32`
   |
note: found an item that was configured out
  --> ...\windows-0.58.0\src\Windows\Win32\mod.rs:14:9
   |
14 | pub mod Graphics;
   |         ^^^^^^^^
   = note: the item is gated behind the `Win32_Graphics` feature
```

Environment info:
    OS Name: Microsoft Windows 11 Pro
    OS Version: 10.0.22631 Build 22631
    RustC / Cargo version: 1.78.0

**Comment by wyhaya** [comment]
Try `cargo update` and see if that fixes it

**Comment by nazebzurati** [comment]
This is still happens after running `cargo update`. This happens in [my project's Github Action](https://github.com/nazebzurati/elelem/actions/runs/13624389972/job/38079019416).

**Comment by kayzer184** [comment]
I'm experiencing exactly the same error when building on Windows:

```rust
error[E0433]: failed to resolve: could not find `Graphics` in `Win32`
  --> ...\tauri-plugin-theme-2.1.2\src\platform\windows.rs:52:13
   |
52 |             Graphics::Dwm::{DwmSetWindowAttribute, DWMWA_USE_IMMERSIVE_DARK_MODE},
   |             ^^^^^^^^ could not find `Graphics` in `Win32`
```

**Environment:**
**- OS: Windows 10 (19045)**
**- Rust/Cargo: latest stable version**

I can't figure out if the problem is related to a bug in my library or to incorrect use of tauri-plugin-theme.

**Comment by kayzer184** [comment]
I found a solution to this issue. The problem is caused by conflicts between different versions of the same libraries being used together.

My fix in a [fork](https://github.com/kayzer184/tauri-plugin-theme):

1. **Updated dependencies to latest versions:**
   - Tauri 2.3.1, webview2-com 0.36.0, windows 0.60.0, windows-core 0.60.1

2. **Fixed Windows API compatibility issues:**
   - Added proper imports for BOOL from windows_core
   - Fixed SetPropW and DefWindowProcW calls to match new API

Now the plugin compiles correctly with newer versions of Windows dependencies and works with Tauri 2.3.1.

**Comment by wyhaya** [comment]
@kayzer184 Indeed, this repository hasn't been updated in a while. Would you be willing to submit a pull request?

**Comment by kayzer184** [comment]
> @kayzer184 Indeed, this repository hasn't been updated in a while. Would you be willing to submit a pull request?

@wyhaya I've already submitted a pull request with the updates. You can find it [here](https://github.com/wyhaya/tauri-plugin-theme/pull/21). Let me know if you have any questions or need any adjustments.

**Comment by wyhaya** [comment]
@kayzer184 Thanks, `v2.1.3` has been released!

**Comment by kayzer184** [comment]
@wyhaya As I see, there is an error in the assembly of the darwin version?

**Comment by wyhaya** [comment]
Just `cargo fmt` check, I've already fixed it!

**Comment by kayzer184** [comment]
@nazebzurati @dacobo, if switching to tauri-plugin-theme@2.1.3 helped you, I think we can close this issue.

**Comment by nazebzurati** [comment]
@kayzer184 @wyhaya it's working now; no build errors on Windows. More info [here](https://github.com/nazebzurati/elelem/actions/runs/13749622936/job/38448924217) (task "Run tauri-apps/tauri-actions@v0", line 634).
